
server:
  port: 0
  servlet:
    context-path: /books

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jbdc:postgresql://localhost:5432:/bookstore
    # the below values must be placed in the vault as following:
    # vault kv put secret/service-books spring.datasource.username=service_books
    # vault kv put secret/service-books spring.datasource.password=service_books_12345#
    #username: service_books
    #password: service_books_12345#
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka