
server:
  port: 0
  servlet:
    context-path: /users

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
      health:
        probes:
          enabled: true

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookstore
    # the below values must be placed in the vault as following:
    # vault kv put secret/service-users spring.datasource.username=service_users
    # vault kv put secret/service-users spring.datasource.password=service_users_12345#
    #username: service_users
    #password: service_users_12345#
    initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
        ddl-auto: create
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATE_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka