
server:
  port: 8888
  servlet:
    context-path: /config

management:
  health:
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

spring:
  profiles:
    active: git, vault
  application:
    name: service-config
  cloud:
    config:
      server:
        vault:
          host: 127.0.0.1
          port: 8200
          order: 1
          kv-version: 1
          authentication: TOKEN
          token: <root-token>
        git:
          uri: file://${user.home}/personal/config-repo
          order: 2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
